version: '3'
services:
  backend:
    build:
      context: ./dians-vinarii
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./wine-and-dine-front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"

  api-gateway:
    build:
      context: ./microservices/api-gateway
      dockerfile: Dockerfile

  auth-service:
    build:
      context: ./microservices/microservice2
      dockerfile: Dockerfile

  discovery-service:
    build:
      context: ./microservices/discovery-service
      dockerfile: Dockerfile

  reviews-service:
    build:
      context: ./microservices/reviews-service
      dockerfile: Dockerfile

  winery-service:
    build:
      context: ./microservices/winery-service
      dockerfile: Dockerfile